### ISSUE TITLE
Name Name Name

### ISSUE THREAD

**Issue by ruthetum** [KangJunewoo/PT-helper#3]
이름을 정해보즈아

**Comment by ruthetum** [comment]
https://dict.naver.com/search.nhn?dicQuery=%EB%B0%9C%ED%91%80&query=%EB%B0%9C%ED%91%80&target=dic&query_utf=&isOnlyViewEE=

발푀 + You

사실 밀푀유가 먹고싶었어

**Comment by ruthetum** [comment]
어쨋든 발표에 도움을 주는 애플리케이션니까 
직관적으로 느낌을 줄 수 있게 

- 도움
- 돔

같은 이름도 괜찮은 듯 이름이 어색하지 않으면서
웹 사이트, 플레이스토어나, 앱스토어에 도움, 돔 같은 단어의 애플리케이션은 없음

단점으로 정확히 목적어가 없기 때문에 아쉽기도 한데
잔디처럼 특정 목적어가 없는 경우의 애플리케이션도 있으니까
오히려 입에 달라 붙는 느낌으로 제목을 가고

돔 같은 경우는 도움을 줄인 말이기도 하고 사전적으로 '돔=반구형으로 된 지붕' 이런 의미로
야구장이 돔 구장이면 비(외적인 요소)가 와도 경기를 진행하는데 문제 없는 것처럼 
pdf파일을 웹에 올리면 그걸 모바일기기로 제어하는 우리의 기능이
외적인 요소(USB파일 놓고 왔다던가, 레이저 포인터가 없다던가, 따로 큐카드 준비를 한다던가)에
구애받지 않고 발표를 진행할 수 있다라는 의미도 부가할 수 있을 듯

**Comment by junu-kk** [comment]
PrEsenTation-helpER
피피티 발표도우미, 피터

pitchy
pitch를 easy하게, 피치

발돋움 (희동 아이디어에서 착안)
발표를 돋보이게, 발돋움.

**Comment by Taehyeon-Kim** [comment]
PREZENT
발표를 선물하다. 프레젠테이션에서 ation제외 앞 글자.
약간 언어유희식으로. S 대신 Z사용으로 멋스러움 부여.

**Comment by i-colours-u** [comment]
PT-SANTA

PIXIE
: 픽시라는 요정 이름에서 착안.. 
PT를 도와주는 요정

**Comment by ruthetum** [comment]
발돋움 2
PREZENT 4
DOM 1
발푀유 1

PREZENT 확정
